export const EVENT_FETCH_YOUTUBE = "EVENT_FETCH_YOUTUBE";
export const EVENT_FETCH_TWITTER = "EVENT_FETCH_TWITTER";
export const EVENT_FETCH_REDDIT = "EVENT_FETCH_REDDIT";
export const EVENT_FETCH_NEWS = "EVENT_FETCH_NEWS";
export const EVENT_FETCH_INSTAGRAM = "EVENT_FETCH_INSTAGRAM";
export const EVENT_FETCH_ALL = "EVENT_FETCH_ALL";
export const EVENT_SWAP = "EVENT_SWAP";

export const EVENT_WATCH_YOUTUBE = "EVENT_WATCH_YOUTUBE";
export const EVENT_READ_NEWS = "EVENT_WATCH_NEWS";

export const EVENT_OPEN_YOUTUBE = "EVENT_OPEN_YOUTUBE";
export const EVENT_OPEN_REDDIT = "EVENT_OPEN_REDDIT";
export const EVENT_OPEN_TWITTER = "EVENT_OPEN_TWITTER";
export const EVENT_OPEN_NEWS_SAFARI = "EVENT_OPEN_NEWS_SAFARI";
export const EVENT_OPEN_STATS = "EVENT_OPEN_STATS";

export const EVENT_SHARE_YOUTUBE = "EVENT_SHARE_YOUTUBE";
export const EVENT_SHARE_REDDIT = "EVENT_SHARE_REDDIT";
export const EVENT_SHARE_TWITTER = "EVENT_SHARE_TWITTER";
export const EVENT_SHARE_NEWS = "EVENT_SHARE_NEWS";
export const EVENT_SHARE_WEBVIEW = "EVENT_SHARE_WEBVIEW";

export const EVENT_OPEN_FREE_MERCH = "EVENT_OPEN_FREE_MERCH";
export const EVENT_OPEN_FREE_MONEY = "EVENT_OPEN_FREE_MONEY";
