export const EVENT_FETCH_YOUTUBE = "EVENT_FETCH_YOUTUBE";
export const EVENT_FETCH_TWITTER = "EVENT_FETCH_TWITTER";
export const EVENT_FETCH_REDDIT = "EVENT_FETCH_REDDIT";

export const EVENT_WATCH_YOUTUBE = "EVENT_WATCH_YOUTUBE";

export const EVENT_OPEN_YOUTUBE = "EVENT_OPEN_YOUTUBE";
export const EVENT_OPEN_REDDIT = "EVENT_OPEN_REDDIT";
export const EVENT_OPEN_TWITTER = "EVENT_OPEN_TWITTER";

export const EVENT_SHARE_YOUTUBE = "EVENT_SHARE_YOUTUBE";
export const EVENT_SHARE_REDDIT = "EVENT_SHARE_REDDIT";
export const EVENT_SHARE_TWITTER = "EVENT_SHARE_TWITTER";
