export const UPDATE_THEME = "app/UPDATE_THEME";
export const UPDATE_REDDIT = "app/UPDATE_REDDIT";
export const UPDATE_TWEETS = "app/UPDATE_TWEETS";
export const UPDATE_YOUTUBE = "app/UPDATE_YOUTUBE";
export const UPDATE_YOUTUBE_DAY = "app/UPDATE_YOUTUBE_DAY";
export const UPDATE_YOUTUBE_ALL_TIME = "app/UPDATE_YOUTUBE_ALL_TIME";
