language: python
cache: pip

python:
- '2.7'
- '3.5'
- '3.6'

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial

env:
  global:
  - TWITTER_USERNAME="TweepyDev"
  - AWS_BUCKET="tweepy"
  - USE_REPLAY=1
  - secure: TPQSFGqdl6khXqQqTZ6euROoAmFRnONAlPXD6npvTIIN+fNfnz8lvZtOEWHo2jRPLoU3FyVUhYvTynj6B2hJinulP+RKOMbQ65HCZVHrsitwl1n1QZB5HegQDOYc5q6VTTYn/r8r5tGy35U0O80y1zycTLqSJiXlkdqsSq564pI=

install:
  - pip install -r test_requirements.txt -r requirements.txt
  - pip install coveralls

script:
  - nosetests -v --with-coverage -c tests/travis-tests.cfg

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then coveralls; fi

before_deploy:
  - pip install twine

deploy:
  provider: pypi
  user: jroesslein
  password:
    secure: agApkjsKOSkFI6DiNydyW26r8ASFsTsFK/RHsV1F7CqoERoeAaRAehYy9EGW2Jn2aJzNlagDByfh5xNfClXuRh0GoEfOyjj5AmBm4hMrzc3bwsH+IPU3OQhQtS3aFGNmIkaz2Bz+Dcl5zTmV914N3mqcoGpyMtxyn1Hwc0Xgn6Q=
  distributions: sdist bdist_wheel
  on:
    repo: tweepy/tweepy
    tags: true
