version: '3'
services:
    web:
        build: ./app
        links:
            - db
            - socket
        ports:
            - "80:80"
        volumes:
            - ./app/src:/src
        environment:
            FLASK_DEBUG: 1
    socket:
        build: ./socket
        links:
            - db
        ports:
            - "5000:5000"
        ulimits:
            nofile:
                soft: 20000
                hard: 40000
    redis:
        image: redis
    poller:
        build: ./poller
        environment:
            BUILD_ENV: 'dev'
        links:
            - db
        volumes:
            - ./poller/src:/src
    db:
        image: mysql:5.7
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'db'
        volumes:
          - ./db:/docker-entrypoint-initdb.d/:ro
