version: '3'
services:
    web:
        image: 834155179289.dkr.ecr.us-east-2.amazonaws.com/yanggang:latest # for aws only
        ports:
            - "80:80"
        logging: # for aws only
            driver: awslogs
            options:
                awslogs-group: tutorial
                awslogs-region: us-east-2
                awslogs-stream-prefix: web
    redis:
        image: redis
    poller:
        image: 834155179289.dkr.ecr.us-east-2.amazonaws.com/poller:latest # for aws only
        logging: # for aws only
            driver: awslogs
            options:
                awslogs-group: tutorial
                awslogs-region: us-east-2
                awslogs-stream-prefix: poller