version: '3'
services:
    web:
        build: ./app
        links:
            - db
        ports:
            - "80:80"
#        volumes:
#            - './app/src:/src'
    redis:
        image: redis
    poller:
        build: ./poller
        environment:
            BUILD_ENV: 'dev'
        links:
            - db
#        volumes:
#            - ./poller/src:/src
    db:
        image: mysql:5.7
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'db'
        volumes:
          - ./db:/docker-entrypoint-initdb.d/:ro
