version: '3'
services:
    web:
        build: ./app
        ports:
            - "80:80"
#        volumes:
#            - src
    redis:
        image: redis
    poller:
        build: ./poller
#        volumes:
#            - src
