version: '2'
services:
    web:
        build: ./app
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis
    poller:
        build: ./poller
        volumes:
            - .:/poller
        depends_on:
            - redis